services:
  - type: web
    name: library-backend
    env: node
    plan: free
    branch: main
    repo: https://github.com/imranahamad07/librarymanagementsystem.git
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://imran3111ahamd_db_user:2BILXdJ8OVARwgyX@cluster0.oxsefmk.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        value: somesecretkey
